# Architecture
# arch: ResNet18

# ===== Dataset ===== #
# data: /mnt/data/
set: cifar100
# name: cifar100_0.3_ER_ERK_STR

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_min: 0.01
lr_policy: cosine_lr
warmup_length: 0

# ===== Network training config ===== #
epochs: 160
weight_decay: 0.001 # Change this according to reported numbers in appendix
momentum: 0.9
batch_size: 256
# label_smoothing: None

# ===== Sparsity =========== #
# er_sparse_init: 0.3
# er_sparse_method: ERK
# er_sparsity_file: ER_STR_cifar_0.3_ERK_2.json
conv_type: ConvMask
bn_type: LearnedBatchNorm
init: kaiming_normal
mode: fan_in
nonlinearity: relu
# sparse_function: sigmoid
# sInit_value: -200 # Change this according to reported numbers in appendix

# ===== Hardware setup ===== #
workers: 4
