# config to get 90.23% sparse ResNet50 on ImageNet. Modify this file to get other sparse models.
# Architecture
# arch: ResNet50

# ===== Dataset ===== #
# data: /mnt/data/
set: cifar10
# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr
warmup_length: 0

# ===== Network training config ===== #
epochs: 160
weight_decay: 0.0001 # Change this according to reported numbers in appendix
momentum: 0.9
batch_size: 256
final_prune_epoch: 30
# ===== Sparsity =========== #
er_sparse_method: none
er_sparse_init: 1

conv_type: ConvMask
bn_type: LearnedBatchNorm
init: kaiming_normal
mode: fan_in
nonlinearity: relu
sparse_function: sigmoid
sInit_value: -200 # Change this according to reported numbers in appendix

# ===== Hardware setup ===== #
workers: 4
